import postcss from 'postcss';
import { readFile, writeFile } from 'node:fs/promises';
// B's existing styles are isolated so they cannot leak into the original A design.
let css =
  '/* Generated by scripts/scope-designs.mjs from the B design sources. */\n';
for (const file of ['app/blindspot-theme.css', 'app/city-theme.css']) {
  const tree = postcss.parse(await readFile(file, 'utf8'));
  tree.walkRules((rule) => {
    if (rule.parent?.type === 'atrule' && /keyframes$/i.test(rule.parent.name))
      return;
    rule.selectors = rule.selectors.map((selector) =>
      selector.includes(':root')
        ? selector.replaceAll(':root', 'html[data-design="b"]')
        : 'html[data-design="b"] ' + selector,
    );
  });
  css += tree.toString() + '\n';
}
css +=
  '\nhtml[data-design="a"] .account-link{font-size:14px;color:#126d60;margin-left:auto;white-space:nowrap}html[data-design="a"] .lang{margin-left:0}html[data-design="a"] .top{gap:22px}\n';
await writeFile('app/designs.css', css);
